    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      
      <?php if ($page->getSeo()); ?>
      <meta name="description" content="<?php echo $page->getMetaDescription(); ?>" />
      <meta name="keywords" content="<?php echo $page->getKeywords(); ?>" />
      
      <?php else: ?>
     
      <meta name="robots" content="noindex, nofollow, noarchive" />
      <?php endif; ?>
      
      <title><?php echo $page->getTitle(); ?></title>
      
      <?php foreach ($this->getPluginBag()->getStylesheets() as $style): ?>
      <link href="<?php echo $style; ?>" rel="stylesheet" />
      <?php endforeach; ?>
      
      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    
    <body>
    
    <!-- Your content -->
    
    <?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
    <script src="<?php echo $script; ?>"></script>
    <?php endforeach; ?>
    
    </body>
    </html>
